--- # This is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install httpd
      yum: pkg=httpd state=installed
      notify:
        - Restart HTTPD
    - name: install git
      yum:  pkg=git state=installed
  handlers:
   - name: Restart HTTPD
     service: name=httpd state=started     
