--- # This is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: yes
  tasks:
    - name: copy files from server to client
      copy: src=login.txt dest=/home/ansadmin/
      
     
        
        
     
