--- # This is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: excute a command
      command: bs -blt
      ignore_errors: yes
    - name: install httpd software
      yum:  pkg=webserver state=installed
